#!/usr/bin/env bash
# Auto-generated by tools/migrate_xfj.py
# Pulls upstream state files (large binary HSTAR restart artifacts) from the
# canonical /mnt/share copy into THIS directory, since shipping them in-repo
# would balloon the working tree.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="/mnt/share/HSTAR_Archive/信赖域/hstardeback(参数反演）/hstar(programandexamples)/HSTAR/典型算例文件/xfj_new/变化渗流场"

if [[ ! -d "$SRC" ]]; then
  echo "ERROR: upstream source not mounted: $SRC" >&2
  echo "Make sure /mnt/share is mounted, or copy the original xfj_new manually." >&2
  exit 1
fi

FILES=("1.gpv" "1.inw" "1.res" "1.resb" "1.rtt" "1.upf")
for f in "${FILES[@]}"; do
  s="$SRC/$f"
  d="$HERE/$f"
  if [[ -f "$s" ]]; then
    if [[ -L "$d" || -f "$d" ]]; then rm -f "$d"; fi
    ln -s "$s" "$d"
    echo "linked  $f  ($(stat -c%s "$s") bytes)"
  fi
done
echo "[xfj prepare] done — case is ready to run."
